=== ritafermad/DTDs/DTD-5/5.2.dtd
<!ELEMENT libreta-direcciones (entrada)*>
<!ELEMENT entrada (nombre, direccion, telefono+, correo-e+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (calle, region, codigo-postal, localidad, pais)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT codigo-postal (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo-e EMPTY>
<!ATTLIST correo-e href CDATA #REQUIRED>
]>

=== ritafermad/DTDs/DTD-5/5.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreta-direcciones SYSTEM "5.2.dtd">
<libreta-direcciones>
  <entrada>
    <nombre>Juan Nadie</nombre>
    <direccion>
      <calle>34 Plaza Vacía</calle>
      <region>Asturias</region>
      <codigo-postal>33203</codigo-postal>
      <localidad>Desconocida</localidad>
      <pais>Sin Tierra</pais>
    </direccion>
    <telefono>513-555-8889</telefono>
    <correo-e href="mailto:jnadie@sincorreo.com"/>
    </entrada>
    </libreta-direcciones>
